#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
INIT_DEBUG=off
[ -f /etc/init.d.conf ] && . /etc/init.d.conf
debug=false
case "${INIT_DEBUG}" in
	true|TRUE|True|yes|YES|Yes|on|ON|On)
		debug=true
		;;
esac
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
     "${debug}" && echo "<6>rcS: ${i}" > /dev/kmsg

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

