################################################################################
#
# tinymembench
#
################################################################################

TINYMEMBENCH_VERSION = 97e26034a5dd02a95aae30a9f281677da6e0a7c8
TINYMEMBENCH_SITE = $(call github,nuumio,tinymembench,$(TINYMEMBENCH_VERSION))
TINYMEMBENCH_LICENSE = MIT
TINYMEMBENCH_LICENSE_FILES = LICENSE

ifeq ($(BR2_TINYMEMBENCH_MEM_REALLOC),y)
TINYMEMBENCH_LATBENCH_REALLOC = 1
else
TINYMEMBENCH_LATBENCH_REALLOC = 0
endif

TINYMEMBENCH_CFLAGS = $(TARGET_CFLAGS)
TINYMEMBENCH_CFLAGS += -D_GNU_SOURCE

define TINYMEMBENCH_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) \
	CFLAGS="$(TINYMEMBENCH_CFLAGS)" \
	MINREPEATS=$(BR2_TINYMEMBENCH_MINREPEATS) \
	MAXREPEATS=$(BR2_TINYMEMBENCH_MAXREPEATS) \
	LATBENCH_REPEATS=$(BR2_TINYMEMBENCH_LATBENCH_REPEATS) \
	LATBENCH_COUNT=$(BR2_TINYMEMBENCH_LATBENCH_COUNT) \
	MEM_REALLOC=$(TINYMEMBENCH_LATBENCH_REALLOC) \
	$(MAKE) -C $(@D)
endef

define TINYMEMBENCH_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/tinymembench \
		$(TARGET_DIR)/usr/bin/tinymembench
endef

$(eval $(generic-package))
